{{- if and (eq .Values.storage.type "s3") (not .Values.storage.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convex-helm.s3SecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "convex-helm.labels" . | nindent 4 }}
type: Opaque
data:
  aws-access-key-id: {{ required "storage.s3.accessKeyId is required when storage.type is s3" .Values.storage.s3.accessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ required "storage.s3.secretAccessKey is required when storage.type is s3" .Values.storage.s3.secretAccessKey | b64enc | quote }}
{{- end }}
