{{- if and (not .Values.instance.existingSecret) .Values.instance.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "convex-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "convex-helm.labels" . | nindent 4 }}
type: Opaque
data:
  instance-secret: {{ .Values.instance.secret | b64enc | quote }}
{{- end }}
